## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [2]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [3]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_1 = X[y == 1]
X_0 = X[y == 0]
y_1 = y[y == 1]
y_0 = y[y == 0]

In [8]:
X_1_train, X_1_test, y_1_train, y_1_test = train_test_split(X_1, y_1, test_size = 10)
X_0_train, X_0_test, y_0_train, y_0_test = train_test_split(X_0, y_0, test_size = 10)

In [19]:
X_test = np.append(X_1_test, X_0_test, axis = 0)
y_test = np.append(y_1_test, y_0_test, axis = 0)

In [20]:
X_test

array([[130, 131, 132, 133, 134],
       [120, 121, 122, 123, 124],
       [100, 101, 102, 103, 104],
       [125, 126, 127, 128, 129],
       [ 15,  16,  17,  18,  19],
       [180, 181, 182, 183, 184],
       [ 70,  71,  72,  73,  74],
       [ 55,  56,  57,  58,  59],
       [ 75,  76,  77,  78,  79],
       [160, 161, 162, 163, 164],
       [675, 676, 677, 678, 679],
       [860, 861, 862, 863, 864],
       [750, 751, 752, 753, 754],
       [545, 546, 547, 548, 549],
       [765, 766, 767, 768, 769],
       [520, 521, 522, 523, 524],
       [315, 316, 317, 318, 319],
       [230, 231, 232, 233, 234],
       [930, 931, 932, 933, 934],
       [330, 331, 332, 333, 334]])

In [21]:
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])