## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
def regression(x_train, x_test, y_train, y_test ):

    # 建立一個線性回歸模型
    lr = linear_model.LinearRegression()

    # 將訓練資料丟進去模型訓練
    lr.fit(x_train, y_train)

    # 將測試資料丟進模型得到預測結果
    y_pred = lr.predict(x_test)
    
    return lr.coef_, mean_squared_error(y_test, y_pred)

def lasso(x_train, x_test, y_train, y_test, alpha_value):
    # 建立一個線性回歸模型
    la = linear_model.Lasso(alpha=alpha_value)

    # 將訓練資料丟進去模型訓練
    la.fit(x_train, y_train)

    # 將測試資料丟進模型得到預測結果
    y_pred = la.predict(x_test)
    
    return la.coef_, mean_squared_error(y_test, y_pred)

def ridge(x_train, x_test, y_train, y_test, alpha_value):
    # 建立一個線性回歸模型
    la = linear_model.Ridge(alpha=alpha_value)

    # 將訓練資料丟進去模型訓練
    la.fit(x_train, y_train)

    # 將測試資料丟進模型得到預測結果
    y_pred = la.predict(x_test)
    
    return la.coef_, mean_squared_error(y_test, y_pred)

In [3]:
boston = datasets.load_boston()

In [4]:
# 切分訓練集/測試
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)

In [5]:
coef, mse = regression(x_train, x_test, y_train, y_test)
print(coef)
print(mse)

[-1.15966452e-01  4.71249231e-02  8.25980146e-03  3.23404531e+00
 -1.66865890e+01  3.88410651e+00 -1.08974442e-02 -1.54129540e+00
  2.93208309e-01 -1.34059383e-02 -9.06296429e-01  8.80823439e-03
 -4.57723846e-01]
25.41958712682191


In [6]:
def test(range_list, x_train, x_test, y_train, y_test):
    for alpha in range_list:
        coef, mse = lasso(x_train, x_test, y_train, y_test, alpha)
        print("alpha : {}".format(alpha))
        print("Lasso coef : {}".format(coef))
        print("MSE : {}".format(mse))
        print("")
        coef, mse = ridge(x_train, x_test, y_train, y_test, alpha)
        print("ridge coef : {}".format(coef))
        print("MSE : {}".format(mse))
        print("")
        print("")

In [7]:
alphas = np.arange(0.1, 1.1, 0.1)
alphas

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [8]:
test(alphas, x_train, x_test, y_train, y_test)

alpha : 0.1
Lasso coef : [-0.10618872  0.04886351 -0.04536655  1.14953069 -0.          3.82353877
 -0.02089779 -1.23590613  0.26008876 -0.01517094 -0.74673362  0.00963864
 -0.49877104]
MSE : 26.45288885360415

ridge coef : [-1.15381303e-01  4.72528249e-02  2.87371589e-03  3.19642306e+00
 -1.54713824e+01  3.89388927e+00 -1.19943742e-02 -1.52347878e+00
  2.90133016e-01 -1.34816989e-02 -8.93679905e-01  8.86599187e-03
 -4.58983115e-01]
MSE : 25.45521174977981


alpha : 0.2
Lasso coef : [-0.10352965  0.04890495 -0.02915034  0.         -0.          3.56522839
 -0.01576328 -1.17371101  0.26651933 -0.01574119 -0.75574867  0.00957983
 -0.52465625]
MSE : 26.603395196601387

ridge coef : [-1.14877966e-01  4.73654143e-02 -1.77329833e-03  3.16231468e+00
 -1.44208162e+01  3.90191854e+00 -1.29375833e-02 -1.50807271e+00
  2.87496280e-01 -1.35481844e-02 -8.82811277e-01  8.91589549e-03
 -4.60110652e-01]
MSE : 25.491958110492916


alpha : 0.30000000000000004
Lasso coef : [-0.09855422  0.04870073 -0.02312

In [9]:
alphas = np.arange(1, 11)
alphas

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
test(alphas, x_train, x_test, y_train, y_test)

alpha : 1
Lasso coef : [-0.06494981  0.04581458 -0.          0.         -0.          1.18140024
  0.01109101 -0.73695809  0.23350042 -0.01551065 -0.69270805  0.00763157
 -0.6927848 ]
MSE : 28.95051203673903

ridge coef : [-1.12499445e-01  4.79562332e-02 -2.40438147e-02  2.96199458e+00
 -9.33966118e+00  3.93079015e+00 -1.73821202e-02 -1.43347691e+00
  2.75239392e-01 -1.38920708e-02 -8.31116943e-01  9.15637729e-03
 -4.66460539e-01]
MSE : 25.743684080012596


alpha : 2
Lasso coef : [-0.0181519   0.03043393 -0.          0.         -0.          0.
  0.03717309 -0.12778153  0.1407538  -0.01207991 -0.54243977  0.00603438
 -0.77311473]
MSE : 34.09393060801163

ridge coef : [-0.11124732  0.04836675 -0.03626675  2.79267166 -6.47851744  3.92986404
 -0.01968654 -1.39130854  0.26915166 -0.01412214 -0.80343978  0.00928963
 -0.47155751]
MSE : 25.931771302149947


alpha : 3
Lasso coef : [-0.          0.02919918 -0.          0.          0.          0.
  0.03886994 -0.          0.03135877 -0.00891871 -0

In [11]:
alphas = np.arange(10, 110, 10)
alphas

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [12]:
test(alphas, x_train, x_test, y_train, y_test)

alpha : 10
Lasso coef : [-0.          0.01832072 -0.          0.          0.          0.
  0.         -0.          0.         -0.01151799 -0.          0.00615268
 -0.52036911]
MSE : 47.626081808641445

ridge coef : [-0.10983294  0.049805   -0.05382756  2.06396836 -1.86500987  3.73850198
 -0.02135944 -1.32033911  0.2667507  -0.01481666 -0.77176853  0.00945631
 -0.49564775]
MSE : 26.23626059940085


alpha : 20
Lasso coef : [-0.          0.02014653 -0.          0.         -0.          0.
 -0.         -0.          0.         -0.0174644  -0.          0.00838957
 -0.236251  ]
MSE : 61.282744491978825

ridge coef : [-0.10981256  0.0508608  -0.05619971  1.59210571 -0.98137565  3.47921666
 -0.01942099 -1.30062498  0.27306321 -0.01523428 -0.77728163  0.00940193
 -0.51775168]
MSE : 26.277636225851857


alpha : 30
Lasso coef : [-0.          0.01829713 -0.          0.         -0.          0.
 -0.         -0.          0.         -0.02252578 -0.          0.0100862
 -0.        ]
MSE : 77.5654037273847

### Lasso 因為某些係數會為 0，故對於訓練結果影響很大，但Ridge相對來說影響比較緩和